# codemagic.yaml
# Codemagic CI/CD configuration for KidsCallHome Android native app
# Reference: https://docs.codemagic.io/yaml-quick-start/building-a-native-android-app/

workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        # Add these groups in Codemagic UI with your credentials:
        # - android_keystore: Contains ANDROID_KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD
        # - google_play: Contains GCLOUD_SERVICE_ACCOUNT_CREDENTIALS (for Play Store publishing)
        - android_keystore
        - google_play
      # Android signing configuration
      # Note: Keystore signing is handled manually in scripts below
      # If you need automatic signing, configure android_signing in Codemagic UI
      # and reference it here as a file reference object
      node: 20
      java: 17
      vars:
        PACKAGE_NAME: "com.kidscallhome.app"
        APP_NAME: "Kids Call Home"
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor Android
        script: |
          # Ensure Android platform is added if it doesn't exist
          if [ ! -d "android" ]; then
            echo "Android directory not found, adding Android platform..."
            npx cap add android
          fi
          # Sync Capacitor
          npx cap sync android
          echo "✅ Capacitor sync completed"
          echo "Checking Android project structure..."
          if [ -d "android" ]; then
            echo "Android directory exists"
            ls -la android/ | head -20
            # Ensure app module is included in settings.gradle
            cd android
            if [ -f "capacitor.settings.gradle" ] && [ ! -f "settings.gradle" ]; then
              echo "Creating settings.gradle from capacitor.settings.gradle..."
              cp capacitor.settings.gradle settings.gradle
            fi
            # Ensure :app module is included in settings.gradle
            if [ -f "settings.gradle" ] && ! grep -q "include ':app'" settings.gradle; then
              echo "⚠️ :app module not found in settings.gradle, adding it..."
              # Prepend include ':app' at the beginning (before other includes)
              echo "include ':app'" > settings.gradle.tmp
              cat settings.gradle >> settings.gradle.tmp
              mv settings.gradle.tmp settings.gradle
              echo "✅ Added include ':app' to settings.gradle"
            fi
            # Verify app module exists
            if [ ! -d "app" ]; then
              echo "❌ app module directory not found. Capacitor sync may have failed."
              echo "Listing android directory contents:"
              ls -la
              exit 1
            fi
            # Verify app/build.gradle exists and uses application plugin
            if [ ! -f "app/build.gradle" ]; then
              echo "⚠️ app/build.gradle not found, checking for capacitor.build.gradle..."
              if [ -f "app/capacitor.build.gradle" ]; then
                echo "Found capacitor.build.gradle, creating app/build.gradle..."
                # Create app/build.gradle with application plugin using echo
                echo "plugins {" > app/build.gradle
                echo "    id 'com.android.application'" >> app/build.gradle
                echo "}" >> app/build.gradle
                echo "apply from: '../capacitor-cordova-android-plugins/cordova.variables.gradle'" >> app/build.gradle
                echo "apply from: 'capacitor.build.gradle'" >> app/build.gradle
                echo "android {" >> app/build.gradle
                echo "    namespace \"com.kidscallhome.app\"" >> app/build.gradle
                echo "    compileSdk rootProject.ext.compileSdkVersion ?: 34" >> app/build.gradle
                echo "    defaultConfig {" >> app/build.gradle
                echo "        applicationId \"com.kidscallhome.app\"" >> app/build.gradle
                echo "        minSdk rootProject.ext.minSdkVersion ?: 22" >> app/build.gradle
                echo "        targetSdk rootProject.ext.targetSdkVersion ?: 34" >> app/build.gradle
                echo "        versionCode 1" >> app/build.gradle
                echo "        versionName \"1.0\"" >> app/build.gradle
                echo "    }" >> app/build.gradle
                echo "    buildTypes {" >> app/build.gradle
                echo "        release {" >> app/build.gradle
                echo "            minifyEnabled false" >> app/build.gradle
                echo "            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'" >> app/build.gradle
                echo "        }" >> app/build.gradle
                echo "    }" >> app/build.gradle
                echo "}" >> app/build.gradle
                echo "dependencies {" >> app/build.gradle
                echo "    implementation fileTree(dir: \"libs\", include: [\"*.jar\"])" >> app/build.gradle
                echo "    implementation project(':capacitor-app')" >> app/build.gradle
                echo "    implementation project(':capacitor-device')" >> app/build.gradle
                echo "    implementation project(':capacitor-haptics')" >> app/build.gradle
                echo "    implementation project(':capacitor-keyboard')" >> app/build.gradle
                echo "    implementation project(':capacitor-local-notifications')" >> app/build.gradle
                echo "    implementation project(':capacitor-push-notifications')" >> app/build.gradle
                echo "    implementation project(':capacitor-splash-screen')" >> app/build.gradle
                echo "    implementation project(':capacitor-status-bar')" >> app/build.gradle
                echo "}" >> app/build.gradle
              else
                echo "❌ Neither app/build.gradle nor app/capacitor.build.gradle found"
                exit 1
              fi
            fi
            cd ..
            if [ ! -f "android/gradlew" ]; then
              echo "⚠️ gradlew not found after sync, initializing Gradle wrapper..."
              cd android
              # Create gradle wrapper directory
              mkdir -p gradle/wrapper
              # Try to use gradle wrapper command if gradle is available
              if command -v gradle >/dev/null 2>&1; then
                echo "Using gradle command to create wrapper..."
                # Create a minimal build.gradle if it doesn't exist
                if [ ! -f "build.gradle" ]; then
                  echo "Creating minimal build.gradle..."
                  echo "// Minimal build.gradle for wrapper generation" > build.gradle
                  echo "buildscript { repositories { mavenCentral() } }" >> build.gradle
                fi
                gradle wrapper --gradle-version 8.2 || {
                  echo "⚠️ Gradle wrapper command failed, trying download method..."
                }
              fi
              # If wrapper still doesn't exist, download wrapper jar from reliable source
              if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
                echo "Downloading gradle-wrapper.jar from CDN..."
                # Download from jsDelivr CDN (serves GitHub files as binaries correctly)
                curl -L https://cdn.jsdelivr.net/gh/gradle/gradle@v8.2.0/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar || {
                  echo "⚠️ CDN download failed, trying direct download..."
                  # Alternative: download from a known working source
                  # The wrapper jar is ~60KB and can be downloaded from Gradle's wrapper repository
                  curl -L "https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradle/wrapper/gradle-wrapper.jar" --output gradle/wrapper/gradle-wrapper.jar --fail || {
                    echo "❌ All download methods failed"
                    echo "Trying to install gradle and use wrapper command..."
                    # Last resort: try to install gradle via homebrew or download
                    if command -v brew >/dev/null 2>&1; then
                      brew install gradle || echo "⚠️ Homebrew install failed"
                      if command -v gradle >/dev/null 2>&1; then
                        gradle wrapper --gradle-version 8.2 || exit 1
                      else
                        exit 1
                      fi
                    else
                      exit 1
                    fi
                  }
                }
              fi
              # Verify wrapper jar exists and is valid
              if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
                echo "❌ gradle-wrapper.jar not found after copy"
                exit 1
              fi
              # Verify file size (wrapper jar should be ~60-70KB)
              JAR_SIZE=$(stat -f%z gradle/wrapper/gradle-wrapper.jar 2>/dev/null || stat -c%s gradle/wrapper/gradle-wrapper.jar 2>/dev/null || echo "0")
              if [ "$JAR_SIZE" -lt 50000 ]; then
                echo "⚠️ Warning: gradle-wrapper.jar seems too small ($JAR_SIZE bytes), may be corrupted"
                echo "File info:"
                ls -lh gradle/wrapper/gradle-wrapper.jar
                # Try to verify it's a valid ZIP/JAR
                if command -v unzip >/dev/null 2>&1; then
                  if ! unzip -t gradle/wrapper/gradle-wrapper.jar >/dev/null 2>&1; then
                    echo "❌ gradle-wrapper.jar is not a valid ZIP/JAR file"
                    exit 1
                  fi
                fi
              fi
              echo "✅ gradle-wrapper.jar downloaded and verified (size: $JAR_SIZE bytes)"
              ls -lh gradle/wrapper/gradle-wrapper.jar
              # Create gradle-wrapper.properties using echo to avoid YAML parsing issues
              echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
              echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
              echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.2-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
              echo "networkTimeout=10000" >> gradle/wrapper/gradle-wrapper.properties
              echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
              echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
              # Create gradlew script using echo
              echo "#!/bin/sh" > gradlew
              echo 'exec java -jar "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" "$@"' >> gradlew
              chmod +x gradlew
              # Verify gradlew and wrapper jar exist
              if [ -f "gradlew" ] && [ -f "gradle/wrapper/gradle-wrapper.jar" ]; then
                echo "✅ Gradle wrapper created and verified"
                ls -lh gradlew gradle/wrapper/gradle-wrapper.jar
              else
                echo "❌ Gradle wrapper verification failed"
                echo "gradlew exists: $([ -f "gradlew" ] && echo "yes" || echo "no")"
                echo "wrapper jar exists: $([ -f "gradle/wrapper/gradle-wrapper.jar" ] && echo "yes" || echo "no")"
                exit 1
              fi
              cd ..
            fi
            if [ -f "android/gradlew" ]; then
              echo "✅ gradlew found/created"
              chmod +x android/gradlew
            else
              echo "❌ Failed to create gradlew"
              exit 1
            fi
          else
            echo "❌ Android directory not found after sync"
            exit 1
          fi
      - name: Set up Android keystore
        script: |
          # Keystore should be uploaded to Codemagic and referenced via environment variables
          # This script assumes keystore is available at $CM_KEYSTORE_PATH
          if [ -z "$CM_KEYSTORE_PATH" ]; then
            echo "⚠️ Keystore path not set. Please configure keystore in Codemagic UI."
            DEBUG_KEYSTORE=~/.android/debug.keystore
            if [ ! -f "$DEBUG_KEYSTORE" ]; then
              echo "Creating a debug keystore for testing..."
              mkdir -p ~/.android
              keytool -genkey -v -keystore "$DEBUG_KEYSTORE" -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
            else
              echo "✅ Debug keystore already exists, skipping creation."
            fi
          else
            echo "✅ Using keystore from CM_KEYSTORE_PATH: $CM_KEYSTORE_PATH"
          fi
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          if [ ! -f "./gradlew" ]; then
            echo "❌ gradlew not found. This should have been created in the sync step."
            exit 1
          fi
          if [ ! -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "❌ gradle-wrapper.jar not found. Checking wrapper directory..."
            ls -la gradle/wrapper/ || echo "gradle/wrapper directory not found"
            exit 1
          fi
          echo "✅ Verifying Gradle wrapper files..."
          ls -lh gradlew gradle/wrapper/gradle-wrapper.jar
          chmod +x ./gradlew
          # Check if settings.gradle exists, if not Capacitor might not have created it
          if [ ! -f "settings.gradle" ]; then
            echo "⚠️ settings.gradle not found, checking if capacitor.settings.gradle exists..."
            if [ -f "capacitor.settings.gradle" ]; then
              echo "Using capacitor.settings.gradle as settings.gradle..."
              cp capacitor.settings.gradle settings.gradle
            else
              echo "❌ No settings.gradle found. Capacitor sync may have failed."
              exit 1
            fi
          fi
          # Check if root build.gradle exists, create minimal one if needed
          if [ ! -f "build.gradle" ]; then
            echo "⚠️ Root build.gradle not found, creating minimal one..."
            echo "buildscript {" > build.gradle
            echo "    repositories {" >> build.gradle
            echo "        google()" >> build.gradle
            echo "        mavenCentral()" >> build.gradle
            echo "    }" >> build.gradle
            echo "    dependencies {" >> build.gradle
            echo "        classpath 'com.android.tools.build:gradle:8.2.1'" >> build.gradle
            echo "    }" >> build.gradle
            echo "}" >> build.gradle
            echo "allprojects {" >> build.gradle
            echo "    repositories {" >> build.gradle
            echo "        google()" >> build.gradle
            echo "        mavenCentral()" >> build.gradle
            echo "    }" >> build.gradle
            echo "}" >> build.gradle
          fi
          # Check available tasks
          echo "Checking available Gradle tasks..."
          ./gradlew tasks --all | grep -i "bundle\|assemble" || echo "No bundle/assemble tasks found"
          # Try building app module directly
          echo "Building Android App Bundle..."
          ./gradlew :app:bundleRelease || {
            echo "⚠️ :app:bundleRelease failed, trying bundleRelease..."
            ./gradlew bundleRelease
          }
      - name: Build APK (optional, for testing)
        script: |
          cd android
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew assembleRelease
          else
            echo "⚠️ gradlew not found, skipping APK build"
          fi
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - justin@fluidinvestmentgroup.com
        notify:
          success: true
          failure: true
      # Uncomment to enable automatic Play Store publishing
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal # Options: internal, alpha, beta, production
      #   submit_as_draft: true
