# codemagic.yaml
# Codemagic CI/CD configuration for KidsCallHome Android native app
# Reference: https://docs.codemagic.io/yaml-quick-start/building-a-native-android-app/

workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        # Add these groups in Codemagic UI with your credentials:
        # - android_keystore: Contains ANDROID_KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD
        # - google_play: Contains GCLOUD_SERVICE_ACCOUNT_CREDENTIALS (for Play Store publishing)
        - android_keystore
        - google_play
      # Android signing configuration
      # Note: Keystore signing is handled manually in scripts below
      # If you need automatic signing, configure android_signing in Codemagic UI
      # and reference it here as a file reference object
      node: 20
      java: 17
      vars:
        PACKAGE_NAME: "com.kidscallhome.app"
        APP_NAME: "Kids Call Home"
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor Android
        script: |
          npx cap sync android
          echo "✅ Capacitor sync completed"
          echo "Checking Android project structure..."
          if [ -d "android" ]; then
            echo "Android directory exists"
            ls -la android/ | head -20
            if [ -f "android/gradlew" ]; then
              echo "✅ gradlew found"
              chmod +x android/gradlew
            else
              echo "⚠️ gradlew not found after sync"
            fi
          else
            echo "❌ Android directory not found after sync"
            exit 1
          fi
      - name: Set up Android keystore
        script: |
          # Keystore should be uploaded to Codemagic and referenced via environment variables
          # This script assumes keystore is available at $CM_KEYSTORE_PATH
          if [ -z "$CM_KEYSTORE_PATH" ]; then
            echo "⚠️ Keystore path not set. Please configure keystore in Codemagic UI."
            DEBUG_KEYSTORE=~/.android/debug.keystore
            if [ ! -f "$DEBUG_KEYSTORE" ]; then
              echo "Creating a debug keystore for testing..."
              mkdir -p ~/.android
              keytool -genkey -v -keystore "$DEBUG_KEYSTORE" -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
            else
              echo "✅ Debug keystore already exists, skipping creation."
            fi
          else
            echo "✅ Using keystore from CM_KEYSTORE_PATH: $CM_KEYSTORE_PATH"
          fi
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          if [ ! -f "./gradlew" ]; then
            echo "❌ gradlew not found. Ensuring Gradle wrapper exists..."
            # Try to generate gradle wrapper if it doesn't exist
            gradle wrapper --gradle-version 8.2 || echo "⚠️ Could not generate gradle wrapper"
          fi
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew bundleRelease
          else
            echo "❌ gradlew still not found after sync. Check Capacitor sync output."
            exit 1
          fi
      - name: Build APK (optional, for testing)
        script: |
          cd android
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew assembleRelease
          else
            echo "⚠️ gradlew not found, skipping APK build"
          fi
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      # Uncomment to enable automatic Play Store publishing
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal # Options: internal, alpha, beta, production
      #   submit_as_draft: true

