# codemagic.yaml
# Codemagic CI/CD configuration for KidsCallHome Android native app
# Simplified version - requires Android project to be properly committed

workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_keystore
        - google_play
      node: 20
      java: 17
      vars:
        PACKAGE_NAME: "com.kidscallhome.app"
        APP_NAME: "Kids Call Home"
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Set up Android keystore
        script: |
          if [ ! -z "$CM_KEYSTORE_PATH" ]; then
            echo "✅ Using keystore from CM_KEYSTORE_PATH"
          else
            echo "⚠️ No keystore configured, using debug signing"
          fi

      - name: Verify Java version and configure Gradle
        script: |
          echo "=== Java Environment Setup ==="
          echo "Java version:"
          java -version
          echo ""
          echo "JAVA_HOME before: $JAVA_HOME"

          # Ensure JAVA_HOME is set and points to Java 17
          # Codemagic sets java: 17, but JAVA_HOME might not be set
          if [ -z "$JAVA_HOME" ]; then
            # Try to find Java 17 using macOS java_home utility
            export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null || echo "")
            if [ -z "$JAVA_HOME" ]; then
              # Fallback: find any Java 17+ installation
              export JAVA_HOME=$(/usr/libexec/java_home -v 17+ 2>/dev/null || echo "")
            fi
            echo "Set JAVA_HOME to: $JAVA_HOME"
          fi

          # Verify JAVA_HOME points to a valid Java 17 installation
          if [ ! -z "$JAVA_HOME" ] && [ -f "$JAVA_HOME/bin/java" ]; then
            echo "JAVA_HOME after: $JAVA_HOME"
            echo "Java version from JAVA_HOME:"
            "$JAVA_HOME/bin/java" -version
            JAVA_VERSION_OUTPUT=$("$JAVA_HOME/bin/java" -version 2>&1)
            if echo "$JAVA_VERSION_OUTPUT" | grep -qE 'version "1\.[0-8]\.'; then
              echo "❌ ERROR: JAVA_HOME points to Java 8 or earlier!"
              echo "Java version output: $JAVA_VERSION_OUTPUT"
              exit 1
            fi
            echo "✅ Java version is 11+"
          else
            echo "❌ ERROR: JAVA_HOME is not set or invalid!"
            echo "Please ensure java: 17 is set in Codemagic environment"
            exit 1
          fi

          # Export JAVA_HOME for this script step
          export JAVA_HOME

          # Configure Gradle to use Java 17
          cd android
          chmod +x ./gradlew

          # Stop any existing Gradle daemons (they might be using Java 8)
          echo ""
          echo "=== Stopping Gradle daemons ==="
          ./gradlew --stop || true
          echo "✅ Gradle daemons stopped"

          # Set org.gradle.java.home in gradle.properties to ensure Gradle uses Java 17
          # This is critical for buildscript classpath resolution
          echo ""
          echo "=== Configuring Gradle to use Java 17 ==="
          if [ -f gradle.properties ]; then
            # Remove any existing org.gradle.java.home line (macOS compatible sed)
            sed -i '' '/^org\.gradle\.java\.home=/d' gradle.properties 2>/dev/null || \
            sed -i.bak '/^org\.gradle\.java\.home=/d' gradle.properties 2>/dev/null || \
            grep -v '^org\.gradle\.java\.home=' gradle.properties > gradle.properties.tmp && mv gradle.properties.tmp gradle.properties
            # Add the correct Java home
            echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
            echo "✅ Updated gradle.properties with org.gradle.java.home=$JAVA_HOME"
            echo "Verification - org.gradle.java.home setting:"
            grep "org.gradle.java.home" gradle.properties || echo "⚠️ Warning: org.gradle.java.home not found in gradle.properties"
          else
            echo "org.gradle.java.home=$JAVA_HOME" > gradle.properties
            echo "✅ Created gradle.properties with org.gradle.java.home=$JAVA_HOME"
          fi

          # Verify Gradle wrapper will use correct Java
          echo ""
          echo "=== Verifying Gradle wrapper configuration ==="
          echo "Gradle wrapper will use: $JAVA_HOME/bin/java"

      - name: Build Android App Bundle
        script: |
          cd android
          # JAVA_HOME should be set from previous step via CM_ENV
          # But ensure it's set just in case
          if [ -z "$JAVA_HOME" ]; then
            export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          fi
          export JAVA_HOME
          echo "Building with JAVA_HOME: $JAVA_HOME"
          ./gradlew bundleRelease --stacktrace

      - name: Build APK (for testing)
        script: |
          cd android
          # JAVA_HOME should be set from previous step via CM_ENV
          # But ensure it's set just in case
          if [ -z "$JAVA_HOME" ]; then
            export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          fi
          export JAVA_HOME
          echo "Building with JAVA_HOME: $JAVA_HOME"
          ./gradlew assembleRelease --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - justin@fluidinvestmentgroup.com
        notify:
          success: true
          failure: true
