# codemagic.yaml
# Codemagic CI/CD configuration for KidsCallHome Android native app
# Simplified version - requires Android project to be properly committed

workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_keystore
        - google_play
      node: 20
      java: 17
      vars:
        PACKAGE_NAME: "com.kidscallhome.app"
        APP_NAME: "Kids Call Home"
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Set up Android keystore
        script: |
          if [ ! -z "$CM_KEYSTORE_PATH" ]; then
            echo "✅ Using keystore from CM_KEYSTORE_PATH"
          else
            echo "⚠️ No keystore configured, using debug signing"
          fi

      - name: Verify Java version and configure Gradle
        script: |
          echo "=== Java Environment Setup ==="
          echo "Java version:"
          java -version
          echo ""
          echo "JAVA_HOME before: $JAVA_HOME"

          # Ensure JAVA_HOME is set and points to Java 17
          # Codemagic sets java: 17, but JAVA_HOME might not be set
          if [ -z "$JAVA_HOME" ]; then
            # Try to find Java 17 using macOS java_home utility
            export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null || echo "")
            if [ -z "$JAVA_HOME" ]; then
              # Fallback: find any Java 17+ installation
              export JAVA_HOME=$(/usr/libexec/java_home -v 17+ 2>/dev/null || echo "")
            fi
            echo "Set JAVA_HOME to: $JAVA_HOME"
          fi

          # Verify JAVA_HOME points to a valid Java 17 installation
          if [ ! -z "$JAVA_HOME" ] && [ -f "$JAVA_HOME/bin/java" ]; then
            echo "JAVA_HOME after: $JAVA_HOME"
            echo "Java version from JAVA_HOME:"
            "$JAVA_HOME/bin/java" -version
            JAVA_VERSION_OUTPUT=$("$JAVA_HOME/bin/java" -version 2>&1)
            if echo "$JAVA_VERSION_OUTPUT" | grep -qE 'version "1\.[0-8]\.'; then
              echo "❌ ERROR: JAVA_HOME points to Java 8 or earlier!"
              echo "Java version output: $JAVA_VERSION_OUTPUT"
              exit 1
            fi
            echo "✅ Java version is 11+"
          else
            echo "❌ ERROR: JAVA_HOME is not set or invalid!"
            echo "Please ensure java: 17 is set in Codemagic environment"
            exit 1
          fi

          # Export JAVA_HOME for this script step
          export JAVA_HOME

          # Configure Gradle to use Java 17
          cd android
          chmod +x ./gradlew

          # Stop any existing Gradle daemons (they might be using Java 8)
          echo ""
          echo "=== Stopping Gradle daemons ==="
          ./gradlew --stop || true
          echo "✅ Gradle daemons stopped"

          # Set org.gradle.java.home in gradle.properties to ensure Gradle uses Java 17
          # This is critical for buildscript classpath resolution
          echo ""
          echo "=== Configuring Gradle to use Java 17 ==="
          if [ -f gradle.properties ]; then
            # Remove any existing org.gradle.java.home line (macOS compatible sed)
            sed -i '' '/^org\.gradle\.java\.home=/d' gradle.properties 2>/dev/null || \
            sed -i.bak '/^org\.gradle\.java\.home=/d' gradle.properties 2>/dev/null || \
            grep -v '^org\.gradle\.java\.home=' gradle.properties > gradle.properties.tmp && mv gradle.properties.tmp gradle.properties
            # Add the correct Java home
            echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
            echo "✅ Updated gradle.properties with org.gradle.java.home=$JAVA_HOME"
            echo "Verification - org.gradle.java.home setting:"
            grep "org.gradle.java.home" gradle.properties || echo "⚠️ Warning: org.gradle.java.home not found in gradle.properties"
          else
            echo "org.gradle.java.home=$JAVA_HOME" > gradle.properties
            echo "✅ Created gradle.properties with org.gradle.java.home=$JAVA_HOME"
          fi

          # Verify Gradle wrapper will use correct Java
          echo ""
          echo "=== Verifying Gradle wrapper configuration ==="
          echo "Gradle wrapper will use: $JAVA_HOME/bin/java"

      - name: Build Debug APK first (to verify build works)
        script: |
          cd android
          # Ensure JAVA_HOME is set
          if [ -z "$JAVA_HOME" ]; then
            export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null || /usr/libexec/java_home -v 17+ 2>/dev/null || echo "")
          fi
          if [ -z "$JAVA_HOME" ] || [ ! -f "$JAVA_HOME/bin/java" ]; then
            export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          fi
          export JAVA_HOME

          # Ensure gradle.properties has org.gradle.java.home set
          if [ -f gradle.properties ]; then
            if ! grep -q "^org\.gradle\.java\.home=" gradle.properties; then
              echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
            fi
          else
            echo "org.gradle.java.home=$JAVA_HOME" > gradle.properties
          fi

          echo "=== Building Debug APK (to verify build works) ==="
          echo "Running: ./gradlew assembleDebug --stacktrace --info"
          echo ""
          
          # Build with output visible and captured - use unbuffered output
          set -o pipefail  # Ensure pipe failures are caught
          ./gradlew assembleDebug --stacktrace --info 2>&1 | tee debug-build.log
          BUILD_EXIT_CODE=${PIPESTATUS[0]}
          
          echo ""
          echo "=== Build completed with exit code: $BUILD_EXIT_CODE ==="
          echo ""
          
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo "❌ Debug build failed with exit code $BUILD_EXIT_CODE!"
            echo ""
            echo "=== FULL BUILD OUTPUT (showing everything) ==="
            cat debug-build.log
            echo ""
            echo "=== Searching for ERROR/Failed/Exception (with context) ==="
            grep -i -A 10 -B 5 "error\|failed\|exception\|FAILURE" debug-build.log || echo "No obvious error keywords found"
            echo ""
            echo "=== Checking for common issues ==="
            grep -i "signing\|keystore\|missing\|not found\|cannot\|unable\|configuration" debug-build.log | head -30 || echo "No common issues found"
            echo ""
            echo "=== Checking Gradle version and Java ==="
            ./gradlew --version 2>&1 || echo "Gradle version check failed"
            echo ""
            echo "=== Checking if gradle.properties exists ==="
            cat gradle.properties 2>&1 || echo "gradle.properties not found"
            exit 1
          fi
          
          echo "✅ Build succeeded!"

          # Verify debug APK was created (only if build succeeded)
          echo ""
          echo "=== Verifying debug APK was created ==="
          if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "✅ Debug APK created successfully!"
            ls -lh app/build/outputs/apk/debug/
          else
            echo "⚠️ Debug APK not found at expected location"
            echo "Searching for APK files..."
            find . -name "*.apk" -type f 2>/dev/null | head -10 || echo "No APK files found anywhere"
            echo ""
            echo "Checking build outputs directory:"
            ls -la app/build/outputs/ 2>/dev/null || echo "app/build/outputs does not exist"
            ls -la app/build/ 2>/dev/null || echo "app/build does not exist"
          fi

      - name: Build Android App Bundle
        script: |
          cd android
          # Ensure JAVA_HOME is set (environment variables don't persist between steps)
          if [ -z "$JAVA_HOME" ]; then
            export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null || /usr/libexec/java_home -v 17+ 2>/dev/null || echo "")
          fi
          if [ -z "$JAVA_HOME" ] || [ ! -f "$JAVA_HOME/bin/java" ]; then
            echo "❌ ERROR: JAVA_HOME is not set or invalid!"
            echo "Attempting to find Java 17..."
            export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          fi
          export JAVA_HOME
          echo "Building with JAVA_HOME: $JAVA_HOME"

          # Ensure gradle.properties has org.gradle.java.home set (it should from previous step, but verify)
          if [ -f gradle.properties ]; then
            if ! grep -q "^org\.gradle\.java\.home=" gradle.properties; then
              echo "Setting org.gradle.java.home in gradle.properties..."
              echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
            fi
          else
            echo "Creating gradle.properties with org.gradle.java.home..."
            echo "org.gradle.java.home=$JAVA_HOME" > gradle.properties
          fi

          # Verify Java version
          echo "Java version:"
          "$JAVA_HOME/bin/java" -version

          # Clean build to ensure fresh state
          echo ""
          echo "=== Cleaning previous build ==="
          ./gradlew clean || true

          # Build with full error output
          echo ""
          echo "=== Building Android App Bundle (Release) ==="
          ./gradlew bundleRelease --stacktrace 2>&1 | tee release-build.log || {
            echo ""
            echo "❌ Release build failed!"
            echo ""
            echo "=== Full build output ==="
            cat release-build.log
            echo ""
            echo "=== Searching for specific errors ==="
            grep -i "signing\|keystore\|password\|error\|failed\|exception" release-build.log | head -30
            echo ""
            echo "⚠️ Release build failed. This might be due to missing signing configuration."
            echo "Trying to build debug bundle instead..."
            ./gradlew bundleDebug --stacktrace 2>&1 | tee debug-bundle.log || {
              echo "Debug bundle also failed:"
              cat debug-bundle.log
              exit 1
            }
          }

          # Verify build artifacts were created
          echo ""
          echo "=== Verifying build artifacts ==="
          echo "Checking for AAB files..."
          find app/build/outputs -name "*.aab" -type f 2>/dev/null | head -10 || echo "No AAB files found"
          echo ""
          echo "Checking for APK files..."
          find app/build/outputs -name "*.apk" -type f 2>/dev/null | head -10 || echo "No APK files found"
          echo ""
          echo "Listing app/build/outputs directory structure:"
          ls -laR app/build/outputs/ 2>/dev/null | head -50 || echo "Outputs directory not found"
          echo ""
          echo "Full path to outputs:"
          pwd
          ls -la app/build/outputs/bundle/release/ 2>/dev/null || echo "Bundle release directory not found"
          ls -la app/build/outputs/apk/release/ 2>/dev/null || echo "APK release directory not found"

      - name: Build Release APK (for testing)
        script: |
          cd android
          # Ensure JAVA_HOME is set (environment variables don't persist between steps)
          if [ -z "$JAVA_HOME" ]; then
            export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null || /usr/libexec/java_home -v 17+ 2>/dev/null || echo "")
          fi
          if [ -z "$JAVA_HOME" ] || [ ! -f "$JAVA_HOME/bin/java" ]; then
            echo "❌ ERROR: JAVA_HOME is not set or invalid!"
            export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          fi
          export JAVA_HOME
          echo "Building with JAVA_HOME: $JAVA_HOME"

          # Ensure gradle.properties has org.gradle.java.home set
          if [ -f gradle.properties ]; then
            if ! grep -q "^org\.gradle\.java\.home=" gradle.properties; then
              echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
            fi
          else
            echo "org.gradle.java.home=$JAVA_HOME" > gradle.properties
          fi

          # Build with full error output
          echo ""
          echo "=== Building Android Release APK ==="
          ./gradlew assembleRelease --stacktrace 2>&1 | tee release-apk.log || {
            echo ""
            echo "❌ Release APK build failed!"
            echo ""
            echo "=== Full build output ==="
            cat release-apk.log
            echo ""
            echo "=== Searching for specific errors ==="
            grep -i "signing\|keystore\|password\|error\|failed\|exception" release-apk.log | head -30
            echo ""
            echo "⚠️ Release APK build failed. Debug APK should already be available from earlier step."
            # Don't exit - debug APK is already built
          }

          # Verify build artifacts were created
          echo ""
          echo "=== Verifying build artifacts ==="
          echo "Checking for APK files..."
          find app/build/outputs -name "*.apk" -type f 2>/dev/null | head -10 || echo "No APK files found"
          echo ""
          echo "Listing app/build/outputs directory structure:"
          ls -laR app/build/outputs/ 2>/dev/null | head -50 || echo "Outputs directory not found"
          echo ""
          echo "Full path to outputs:"
          pwd
          ls -la app/build/outputs/apk/release/ 2>/dev/null || echo "APK release directory not found"
          ls -la app/build/outputs/apk/debug/ 2>/dev/null || echo "APK debug directory not found"

      - name: Verify artifacts from workspace root
        script: |
          echo "=== Verifying artifacts from workspace root ==="
          echo "Current directory: $(pwd)"
          echo ""
          echo "Looking for AAB files:"
          find . -name "*.aab" -type f 2>/dev/null | head -10 || echo "No AAB files found"
          echo ""
          echo "Looking for APK files:"
          find . -name "*.apk" -type f 2>/dev/null | head -10 || echo "No APK files found"
          echo ""
          echo "Checking android/app/build/outputs:"
          if [ -d "android/app/build/outputs" ]; then
            echo "✅ Outputs directory exists"
            ls -laR android/app/build/outputs/ | head -100
          else
            echo "❌ Outputs directory does not exist!"
            echo "Listing android/app/build directory:"
            ls -la android/app/build/ 2>/dev/null || echo "android/app/build does not exist"
          fi

      - name: Artifact Summary and Download Instructions
        script: |
          echo "=========================================="
          echo "📦 ARTIFACT SUMMARY"
          echo "=========================================="
          echo ""
          echo "Finding all APK and AAB files:"
          find . -type f \( -name "*.apk" -o -name "*.aab" \) 2>/dev/null | while read file; do
            echo "  ✅ Found: $file ($(du -h "$file" | cut -f1))"
          done || echo "  ⚠️ No APK/AAB files found"
          echo ""
          echo "=========================================="
          echo "📥 HOW TO DOWNLOAD ARTIFACTS"
          echo "=========================================="
          echo ""
          echo "After a successful build, download your app files from Codemagic:"
          echo ""
          echo "1. Go to your Codemagic dashboard"
          echo "2. Click on the completed build"
          echo "3. Scroll to the 'Artifacts' section"
          echo "4. Click the download button next to:"
          echo "   - *.apk files (for direct installation)"
          echo "   - *.aab files (for Google Play Store upload)"
          echo ""
          echo "Or use the Codemagic CLI:"
          echo "  codemagic-cli builds artifacts <build-id>"
          echo ""
          echo "Artifacts are automatically collected from:"
          echo "  - android/app/build/outputs/**/*.apk"
          echo "  - android/app/build/outputs/**/*.aab"
          echo ""

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/bundle/**/*
      - android/app/build/outputs/apk/**/*
      - android/app/build/outputs/**/debug/**
      - android/app/build/outputs/**/release/**

    publishing:
      email:
        recipients:
          - justin@fluidinvestmentgroup.com
        notify:
          success: true
          failure: true
