# codemagic.yaml
# Codemagic CI/CD configuration for KidsCallHome Android native app
# Simplified version - requires Android project to be properly committed

workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_keystore
        - google_play
      node: 20
      java: 17
      vars:
        PACKAGE_NAME: "com.kidscallhome.app"
        APP_NAME: "Kids Call Home"
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Build web app
        script: |
          npm run build
          
      - name: Sync Capacitor
        script: |
          npx cap sync android
          
      - name: Set up Android keystore
        script: |
          if [ ! -z "$CM_KEYSTORE_PATH" ]; then
            echo "✅ Using keystore from CM_KEYSTORE_PATH"
          else
            echo "⚠️ No keystore configured, using debug signing"
          fi
          
      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew bundleRelease --stacktrace
          
      - name: Build APK (for testing)
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
          
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - justin@fluidinvestmentgroup.com
        notify:
          success: true
          failure: true
