// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeLog } from '@/utils/security';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug logging (only in development)
safeLog.log('🔍 [SUPABASE CLIENT] Environment check:', {
  hasUrl: !!SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  urlLength: SUPABASE_URL?.length || 0,
  keyLength: SUPABASE_PUBLISHABLE_KEY?.length || 0,
  mode: import.meta.env.MODE,
  dev: import.meta.env.DEV,
  prod: import.meta.env.PROD,
});

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingVars = [];
  if (!SUPABASE_URL) missingVars.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  safeLog.error(
    `❌ Missing required environment variables: ${missingVars.join(', ')}\n` +
    `Please set these in your Vercel project settings or .env file.\n` +
    `The app will not function without these variables.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with error handling
let supabase: ReturnType<typeof createClient<Database>>;

try {
  supabase = createClient<Database>(
    SUPABASE_URL || 'https://placeholder.supabase.co',
    SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
    {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: false, // Prevent auto-redirect on auth errors
      },
      realtime: {
        params: {
          eventsPerSecond: 10,
        },
      },
      global: {
        headers: {
          'x-client-info': 'kidscallhome-web',
        },
      },
    }
  );
} catch (error) {
  safeLog.error('❌ [SUPABASE CLIENT] Failed to create client:', error);
  // Create a minimal client to prevent app crash
  supabase = createClient<Database>(
    'https://placeholder.supabase.co',
    'placeholder-key',
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    }
  );
}

export { supabase };

// Handle auth errors gracefully - clear invalid tokens
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    // Token refreshed successfully
    if (import.meta.env.DEV) {
      safeLog.log('✅ [AUTH] Token refreshed successfully');
    }
  } else if (event === 'SIGNED_OUT') {
    // User signed out - clear any stale session data
    if (import.meta.env.DEV) {
      safeLog.log('🔓 [AUTH] User signed out');
    }
  }
});

// Global error handler for auth refresh failures
// This catches errors that occur during automatic token refresh
if (typeof window !== 'undefined') {
  // Listen for unhandled promise rejections from Supabase auth
  const originalErrorHandler = window.onerror;
  window.addEventListener('unhandledrejection', (event) => {
    const error = event.reason;
    // Check if it's a Supabase auth error with invalid refresh token
    if (error?.message?.includes('Invalid Refresh Token') || 
        error?.message?.includes('Refresh Token Not Found')) {
      // Clear invalid session data
      if (import.meta.env.DEV) {
        safeLog.debug('🔄 [AUTH] Clearing invalid refresh token');
      }
      
      // Clear Supabase auth data from localStorage
      const supabaseKeys = Object.keys(localStorage).filter(key => 
        key.startsWith('sb-') && key.includes('auth-token')
      );
      supabaseKeys.forEach(key => localStorage.removeItem(key));
      
      // Prevent the error from showing in console
      event.preventDefault();
      
      // Optionally sign out to clear all session data
      supabase.auth.signOut({ scope: 'local' }).catch(() => {
        // Ignore errors during cleanup
      });
    }
  });
}